# src/orchestrator/checkpoint_manager.py
"""
Checkpoint manager for workflow state persistence.
"""

import os
from typing import Optional, List
from datetime import datetime
from ..models.checkpoint import Checkpoint
from ..models.workflow_state import WorkflowState
from ..utils.storage import storage
from ..utils.config import config


class CheckpointManagerError(Exception):
    """Base exception for checkpoint manager errors."""
    pass


class CheckpointManager:
    """
    Manages checkpointing of workflow state for resumability.
    """
    
    def __init__(self):
        """Initialize checkpoint manager."""
        self.storage = storage
        self.config = config
        self.checkpoint_interval = config.get("checkpoint_interval_seconds", 300)
        self.retention_count = config.get("checkpoint_retention_count", 10)
        self.last_checkpoint_time: Optional[datetime] = None
    
    def should_checkpoint(self) -> bool:
        """
        Determine if a checkpoint should be created based on time interval.
        
        Returns:
            True if enough time has passed since last checkpoint, False otherwise
        """
        if self.last_checkpoint_time is None:
            return True
        
        elapsed = (datetime.utcnow() - self.last_checkpoint_time).total_seconds()
        return elapsed >= self.checkpoint_interval
    
    def create_checkpoint(self, workflow_state: WorkflowState, 
                         current_step: str,
                         decision_log_reference: dict) -> Checkpoint:
        """
        Create a new checkpoint from workflow state.
        
        Args:
            workflow_state: Current workflow state
            current_step: Stage ID where execution is paused/resumed
            decision_log_reference: Reference to decision log (logId and entryCount)
            
        Returns:
            Created Checkpoint instance
            
        Raises:
            CheckpointManagerError: If checkpoint cannot be created
        """
        try:
            checkpoint = Checkpoint(
                checkpoint_id="",  # Will be generated by storage
                timestamp=datetime.utcnow(),
                workflow_id=workflow_state.workflow_id,
                current_step=current_step,
                state=workflow_state,
                decision_log_reference=decision_log_reference,
                version="1.0.0"
            )
            
            # Save to storage
            checkpoint_id = self.storage.save_checkpoint(checkpoint)
            checkpoint.checkpoint_id = checkpoint_id
            
            self.last_checkpoint_time = checkpoint.timestamp
            
            # Clean up old checkpoints if needed
            self._cleanup_old_checkpoints(workflow_state.workflow_id)
            
            return checkpoint
        except Exception as e:
            raise CheckpointManagerError(f"Failed to create checkpoint: {e}")
    
    def load_latest_checkpoint(self, workflow_id: str) -> Optional[Checkpoint]:
        """
        Load the latest checkpoint for a workflow.
        
        Args:
            workflow_id: ID of the workflow
            
        Returns:
            Latest Checkpoint instance or None if no checkpoints exist
        """
        try:
            checkpoint_ids = self.storage.list_checkpoints(workflow_id)
            if not checkpoint_ids:
                return None
            
            # Load the most recent checkpoint (last in the sorted list)
            latest_checkpoint_id = checkpoint_ids[-1]
            return self.storage.load_checkpoint(latest_checkpoint_id)
        except Exception as e:
            raise CheckpointManagerError(f"Failed to load latest checkpoint for workflow {workflow_id}: {e}")
    
    def load_checkpoint(self, checkpoint_id: str) -> Checkpoint:
        """
        Load a specific checkpoint by ID.
        
        Args:
            checkpoint_id: ID of the checkpoint to load
            
        Returns:
            Checkpoint instance
            
        Raises:
            CheckpointManagerError: If checkpoint cannot be loaded
        """
        try:
            return self.storage.load_checkpoint(checkpoint_id)
        except Exception as e:
            raise CheckpointManagerError(f"Failed to load checkpoint {checkpoint_id}: {e}")
    
    def list_checkpoints(self, workflow_id: Optional[str] = None) -> List[str]:
        """
        List available checkpoint IDs.
        
        Args:
            workflow_id: Optional workflow ID to filter by
            
        Returns:
            List of checkpoint IDs
        """
        return self.storage.list_checkpoints(workflow_id)
    
    def delete_checkpoint(self, checkpoint_id: str) -> bool:
        """
        Delete a checkpoint from storage.
        
        Args:
            checkpoint_id: ID of the checkpoint to delete
            
        Returns:
            True if deleted, False if not found
        """
        return self.storage.delete_checkpoint(checkpoint_id)
    
    def _cleanup_old_checkpoints(self, workflow_id: str) -> None:
        """
        Delete old checkpoints beyond the retention limit.
        
        Args:
            workflow_id: ID of the workflow
        """
        try:
            checkpoint_ids = self.storage.list_checkpoints(workflow_id)
            # Keep only the most recent retention_count checkpoints
            if len(checkpoint_ids) > self.retention_count:
                ids_to_delete = checkpoint_ids[:-self.retention_count]
                for checkpoint_id in ids_to_delete:
                    self.storage.delete_checkpoint(checkpoint_id)
        except Exception:
            # Don't let cleanup errors break checkpoint creation
            pass