#!/usr/bin/env python3
"""
Transcription Agent for Ellio Pipeline.
Handles speech-to-text transcription of video/audio files.
"""

import sys
import os
import json
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent))

from base_agent import BaseAgent, main


class TranscriptionAgent(BaseAgent):
    """Agent for transcribing video/audio to text."""
    
    def __init__(self):
        super().__init__("transcription-agent")
    
    def run(self) -> int:
        """Execute the transcription stage."""
        self.log("Starting transcription")
        
        # Get input video location
        input_location = self.get_input_location(0)
        if not input_location:
            self.log("No input video provided", "ERROR")
            return 1
        
        self.log(f"Input video: {input_location}")
        
        # Get output location
        output_location = self._get_output_location()
        if not output_location:
            self.log("No output location specified", "ERROR")
            return 1
        
        self.log(f"Output transcript: {output_location}")
        
        # Resolve file paths
        src_path = self.resolve_file_path(input_location)
        dst_path = self.resolve_file_path(output_location)
        
        if not src_path or not dst_path:
            self.log("Invalid file URIs", "ERROR")
            return 1
        
        if not src_path.exists():
            self.log(f"Source file does not exist: {src_path}", "ERROR")
            return 1
        
        # For MVP, we'll create a mock transcript since actual transcription
        # would require external tools like whisper, ffmpeg, etc.
        # In a real implementation, this would call whisper.cpp or similar
        
        transcript_data = self._create_mock_transcript(src_path)
        
        # Write transcript JSON
        try:
            dst_path.parent.mkdir(parents=True, exist_ok=True)
            with open(dst_path, 'w', encoding='utf-8') as f:
                json.dump(transcript_data, f, indent=2, ensure_ascii=False)
            
            self.log("Transcription completed successfully")
            return 0
        except Exception as e:
            self.log(f"Failed to write transcript: {e}", "ERROR")
            return 1
    
    def _get_output_location(self) -> Optional[str]:
        """Get the output location from environment."""
        for key, value in os.environ.items():
            if key.startswith("OUTPUT_") and key.endswith("_LOCATION"):
                return value
        return self.parameters.get("output_location")
    
    def _create_mock_transcript(self, video_path: Path) -> dict:
        """Create a mock transcript for MVP. In production, this would use whisper or similar."""
        # Get video duration using ffprobe if available
        duration = self._get_video_duration(video_path)
        
        # Create mock transcript structure matching expected schema
        transcript = {
            "language": "en",
            "duration": duration,
            "segments": [
                {
                    "id": 0,
                    "start": 0.0,
                    "end": min(5.0, duration),
                    "text": "This is a mock transcript generated by the MVP transcription agent.",
                    "confidence": 0.95
                }
            ],
            "metadata": {
                "source_file": str(video_path),
                "generated_at": datetime.utcnow().isoformat() + "Z",
                "agent": "transcription-agent",
                "model": "mock-model-v1"
            }
        }
        
        # Add more segments if video is longer
        if duration > 5.0:
            segment_count = int(duration / 5.0) + 1
            for i in range(1, segment_count):
                start = i * 5.0
                end = min(start + 5.0, duration)
                transcript["segments"].append({
                    "id": i,
                    "start": start,
                    "end": end,
                    "text": f"Mock transcript segment {i+1} from {start:.1f}s to {end:.1f}s.",
                    "confidence": 0.90
                })
        
        return transcript
    
    def _get_video_duration(self, video_path: Path) -> float:
        """Get video duration using ffprobe if available."""
        try:
            import subprocess
            result = subprocess.run([
                "ffprobe", "-v", "error", "-show_entries",
                "format=duration", "-of", "default=noprint_wrappers=1:nokey=1",
                str(video_path)
            ], capture_output=True, text=True, timeout=30)
            if result.returncode == 0 and result.stdout.strip():
                return float(result.stdout.strip())
        except Exception:
            pass
        
        # Default duration if ffprobe not available
        return 10.0


def create_agent() -> BaseAgent:
    return TranscriptionAgent()


if __name__ == "__main__":
    main()